// Code generated by protoc-gen-go.
// source: test1.proto
// DO NOT EDIT!

/*
Package protodata is a generated protocol buffer package.

It is generated from these files:
	test1.proto
	test.proto

It has these top-level messages:
	Test1
	Test2
	Test
*/
package protodata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Test1_EDEMO int32

const (
	Test1_UNKNOWN Test1_EDEMO = 0
	Test1_X       Test1_EDEMO = 17
	Test1_Y       Test1_EDEMO = 18
)

var Test1_EDEMO_name = map[int32]string{
	0:  "UNKNOWN",
	17: "X",
	18: "Y",
}
var Test1_EDEMO_value = map[string]int32{
	"UNKNOWN": 0,
	"X":       17,
	"Y":       18,
}

func (x Test1_EDEMO) String() string {
	return proto.EnumName(Test1_EDEMO_name, int32(x))
}
func (Test1_EDEMO) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Test1 struct {
	Users map[string]int32 `protobuf:"bytes,1,rep,name=users" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Page  int64            `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	Names []string         `protobuf:"bytes,3,rep,name=names" json:"names,omitempty"`
	Ed    Test1_EDEMO      `protobuf:"varint,4,opt,name=ed,enum=protodata.Test1_EDEMO" json:"ed,omitempty"`
}

func (m *Test1) Reset()                    { *m = Test1{} }
func (m *Test1) String() string            { return proto.CompactTextString(m) }
func (*Test1) ProtoMessage()               {}
func (*Test1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Test1) GetUsers() map[string]int32 {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Test1) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Test1) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *Test1) GetEd() Test1_EDEMO {
	if m != nil {
		return m.Ed
	}
	return Test1_UNKNOWN
}

type Test2 struct {
	Page  int32  `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
}

func (m *Test2) Reset()                    { *m = Test2{} }
func (m *Test2) String() string            { return proto.CompactTextString(m) }
func (*Test2) ProtoMessage()               {}
func (*Test2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Test2) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Test2) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*Test1)(nil), "protodata.Test1")
	proto.RegisterType((*Test2)(nil), "protodata.Test2")
	proto.RegisterEnum("protodata.Test1_EDEMO", Test1_EDEMO_name, Test1_EDEMO_value)
}

func init() { proto.RegisterFile("test1.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x8f, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x9d, 0x66, 0xa3, 0x74, 0x0a, 0x52, 0x07, 0x91, 0xa0, 0x97, 0xd0, 0x83, 0xe4, 0x54,
	0x68, 0xbd, 0x2c, 0x9e, 0xed, 0x49, 0xec, 0x42, 0x70, 0x51, 0x8f, 0x91, 0x06, 0x11, 0xd7, 0xdd,
	0xa5, 0xc9, 0x0a, 0xfd, 0xcb, 0xfe, 0x0a, 0x49, 0x02, 0xf5, 0xb0, 0xa7, 0x99, 0xc7, 0x3c, 0xbe,
	0xf7, 0x06, 0x0b, 0x6f, 0x9d, 0x6f, 0xea, 0xfd, 0xb8, 0xf3, 0x3b, 0xca, 0xe3, 0x18, 0x8c, 0x37,
	0xd5, 0x2f, 0x20, 0x7f, 0x0e, 0x27, 0x6a, 0x90, 0x1f, 0x9c, 0x1d, 0x9d, 0x00, 0xc9, 0x54, 0xd1,
	0xde, 0xd4, 0xb3, 0xa9, 0x8e, 0x86, 0x7a, 0x1d, 0xae, 0xdd, 0xd6, 0x8f, 0x93, 0x4e, 0x4e, 0x22,
	0x5c, 0xec, 0xcd, 0x87, 0x15, 0x99, 0x04, 0xc5, 0x74, 0xdc, 0xe9, 0x12, 0xf9, 0xd6, 0x7c, 0x5b,
	0x27, 0x98, 0x64, 0x2a, 0xd7, 0x49, 0xd0, 0x2d, 0x66, 0x76, 0x10, 0x0b, 0x09, 0xea, 0xbc, 0xbd,
	0x3a, 0x22, 0x77, 0x0f, 0xdd, 0xd3, 0x4a, 0x67, 0x76, 0xb8, 0x5e, 0x22, 0xfe, 0xc7, 0x50, 0x89,
	0xec, 0xcb, 0x4e, 0x02, 0x24, 0xa8, 0x5c, 0x87, 0x35, 0xd0, 0x7f, 0xcc, 0xe6, 0x90, 0x22, 0xb9,
	0x4e, 0xe2, 0x3e, 0x5b, 0x42, 0x55, 0x21, 0x8f, 0x18, 0x2a, 0xf0, 0x6c, 0xdd, 0x3f, 0xf6, 0xab,
	0x97, 0xbe, 0x3c, 0x21, 0x8e, 0xf0, 0x5a, 0x5e, 0x84, 0xf1, 0x56, 0x52, 0xd5, 0xa4, 0x5f, 0xdb,
	0xb9, 0x38, 0x44, 0xca, 0x5c, 0xdc, 0x7f, 0xfa, 0x4d, 0x42, 0xe7, 0x3a, 0x89, 0xf7, 0xd3, 0xd8,
	0xf5, 0xee, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xed, 0x8b, 0x21, 0x40, 0x01, 0x00, 0x00,
}
